version: "3"

services:
    # https://hub.docker.com/_/mongo/
    mongo:
        container_name: dc-mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        image: mongo:latest
        networks:
            - nw-mongo
        ports:
            - 27017:27017
        restart: always
        tty: true
        volumes:
            - ./mongo-db:/data/db

networks:
    nw-mongo:
        driver: bridge
