version: "3"

services:
    # https://hub.docker.com/_/mongo/
    mongo:
        container_name: dc-mongo
        env_file:
            - mongo.env
        image: mongo:latest
        networks:
            - nw-mongo
        ports:
            - 27017:27017
        restart: always
        tty: true
        volumes:
            - ./mongo-db:/data/db
            # mkdir mongo-home && sudo chown `docker run --rm mongo:latest id -u mongodb`:`docker run --rm mongo:latest id -g mongodb` mongo-home
            - ./mongo-home:/home/mongodb
            - ./mongo-initdb.d:/docker-entrypoint-initdb.d

networks:
    nw-mongo:
        driver: bridge
